#!/bin/bash
# Generate a deterministic ~500 KB Markdown document with 100+ code blocks
# in mixed languages, plus tables, lists, headings, and inline formatting.
# No randomness; running it twice produces identical bytes.

set -euo pipefail

OUTPUT_DIR="${1:-.build/bench}"
mkdir -p "$OUTPUT_DIR"
OUTPUT_FILE="$OUTPUT_DIR/fixture.md"

# Use a temp file and replace atomically so a partial write doesn't corrupt
# an existing fixture.
TEMP_FILE=$(mktemp)
trap "rm -f $TEMP_FILE" EXIT

# Saved so the closing status line below can reach the terminal instead of
# the fixture: `exec >` redirects stdout for the rest of this shell, and
# after `mv` moves $TEMP_FILE to $OUTPUT_FILE, fd 1 is still the same open
# file — now reachable at the new path — so anything written after the move
# without restoring fd 1 first lands inside the "finished" fixture.
exec 3>&1
exec > "$TEMP_FILE"

# Header and introduction.
cat << 'EOF'
# Benchmark Fixture

A deterministic large document for measuring latency. Generated by `make-bench-fixture.sh`.

This document contains 100+ fenced code blocks in various languages, plus tables, lists,
headings, and inline formatting, all designed to exercise the rendering pipeline.

## Overview

The document is organized into sections, each demonstrating different Markdown features
that a real document might contain. Code blocks are the primary cost driver, as they
trigger highlight.js for syntax highlighting.

## Table of Contents

- [Code Blocks](#code-blocks)
- [Lists](#lists)
- [Tables](#tables)
- [Inline Formatting](#inline-formatting)

---

## Code Blocks

This section contains 100+ fenced code blocks in different languages.

EOF

# Generate code blocks in various languages. Each block is large enough to
# exercise the renderer but not so large that a single block dominates.
# We cycle through languages to create variety.

LANGUAGES=(
  "swift"
  "python"
  "javascript"
  "java"
  "go"
  "rust"
  "c"
  "bash"
  "sql"
  "html"
  "css"
  "json"
  "yaml"
  "markdown"
  "xml"
)

# Generate code blocks. We want 100+, so let's make 120 blocks.
for i in {1..120}; do
  LANG_IDX=$((i % ${#LANGUAGES[@]}))
  LANG="${LANGUAGES[$LANG_IDX]}"

  cat << EOF

### Code Block $i ($LANG)

\`\`\`$LANG
// Example code block in $LANG
// This is line 2 of the code block
// This is line 3 of the code block
// This is line 4 of the code block
// This is line 5 of the code block
function example$i() {
  const variable1 = "value1";
  const variable2 = "value2";
  const variable3 = "value3";
  const variable4 = "value4";
  const variable5 = "value5";
  return {
    result: variable1,
    data: variable2,
    status: variable3,
    code: variable4,
    message: variable5
  };
}
\`\`\`

Example $i demonstrates the $LANG language. This is a sentence about the code.
This is another sentence to pad the content. This helps exercise the rendering.

EOF
done

# Add a section with lists.
cat << 'EOF'

---

## Lists

This section demonstrates various list types.

### Unordered List

- Item one in the list
  - Nested item 1.1
  - Nested item 1.2
    - Deeply nested 1.2.1
    - Deeply nested 1.2.2
- Item two in the list
  - Nested item 2.1
- Item three in the list

### Ordered List

1. First item
   1. Nested first
   2. Nested second
2. Second item
   1. Another nested
3. Third item

### Task List

- [x] Completed task one
- [ ] Incomplete task two
- [x] Completed task three
  - [x] Subtask 3.1
  - [ ] Subtask 3.2
- [ ] Incomplete task four

EOF

# Add a section with tables.
cat << 'EOF'

---

## Tables

This section contains tables to exercise table rendering.

### Feature Comparison Table

| Feature | Status | Priority | Notes |
|---------|--------|----------|-------|
| Code highlighting | ✓ | High | Uses highlight.js |
| Live reload | ✓ | High | Watches file for changes |
| Math rendering | ✗ | Medium | Not implemented |
| Mermaid diagrams | ✓ | Medium | Lazy-loaded |
| Table of contents | ✗ | Low | Future enhancement |
| Search | ✓ | High | Native ⌘F support |

### Performance Metrics

| Metric | Cold | Warm | Reload |
|--------|------|------|--------|
| Launch to paint | 250 ms | 50 ms | 75 ms |
| Memory footprint | 120 MB | 120 MB | 120 MB |
| CPU during render | 45% | 25% | 30% |
| First paint | 500 ms | 150 ms | 100 ms |

EOF

# Add inline formatting section.
cat << 'EOF'

---

## Inline Formatting

This section demonstrates inline text formatting and special characters.

Here is some text with **bold**, *italic*, and ***bold italic*** formatting.
This is `inline code` mixed with regular text. And here is a **`bold code`** example.

This is a paragraph with [a link](https://github.com/telday/markdown-viewer) to the repository.
You can also have [links with title text](https://example.com "example title").

Here is a footnote reference[^1] and another[^2].

[^1]: This is the first footnote explaining something important.
[^2]: This is the second footnote with additional detail.

---

### Special Characters and Entities

The following special characters should render correctly:

- Copyright © 2024
- Registered ® symbol
- Trademark ™ symbol
- Ellipsis … character
- Em dash — example
- En dash – example
- Bullet • point
- Degree ° symbol

### Quotes and Emphasis

> This is a blockquote.
> It can span multiple lines.
>
> And have multiple paragraphs.
>
> > And can be nested.

### Horizontal Rules

---

A horizontal rule appears above and below this text.

---

### Links and References

[Link reference style][ref1] allows organizing links at the end of a document.

[ref1]: https://github.com/telday/markdown-viewer

### Images and Alt Text

You can include images with:
![alt text](image.png)

### Code Blocks in Lists

Here's a list with code blocks:

1. First item
   ```swift
   let x = 42
   ```

2. Second item
   ```python
   x = 42
   ```

---

EOF

# Add additional content sections to reach ~500 KB.
for section in {1..140}; do
  cat << EOF

## Additional Section $section

This section adds more content to reach the target file size of approximately 500 KB.
The section contains multiple subsections with code blocks and tables to exercise
the renderer with realistic content patterns found in technical documentation.

### Subsection $section.1

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

Here's another code block for good measure:

\`\`\`javascript
// Code block in section $section
// This function demonstrates data processing
function processData(input) {
  const lines = input.split('\\n');
  return lines
    .map(line => line.trim())
    .filter(line => line.length > 0)
    .reduce((acc, line) => {
      acc[line.split(':')[0]] = line.split(':')[1];
      return acc;
    }, {});
}

const result = processData('name: test\\nstatus: active\\nvalue: 42');
console.log(result);
\`\`\`

### Subsection $section.2

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit
voluptatem accusantium doloremque laudantium.

More text to add to the file size. This is repeated across multiple sections to reach
the target size for benchmarking purposes. Each section is designed to be realistic
and representative of actual documentation.

#### Code Example

\`\`\`python
def process_benchmark_fixture(document_path):
    """Process a benchmark fixture document."""
    with open(document_path, 'r') as f:
        content = f.read()

    # Count various elements
    code_blocks = content.count('\`\`\`')
    tables = content.count('|')
    headings = content.count('#')

    return {
        'code_blocks': code_blocks // 2,  # Each block has opening and closing
        'tables': tables // 4,  # Rough estimate
        'headings': headings
    }
\`\`\`

### Subsection $section.3

Additional details about this section to build content. The benchmark fixture needs
to be large enough to be realistic while remaining fast enough to test frequently.

| Feature | Count | Details |
|---------|-------|---------|
| Code blocks | 120+ | In various languages |
| Sections | 50 | Large sections |
| Tables | Many | For layout rendering |
| Lists | Various | Ordered and unordered |
| Inline styles | Abundant | Bold, italic, code |

### Subsection $section.4

This subsection adds more depth to each major section. The fixture is designed to
exercise all rendering code paths without being unnecessarily large.

\`\`\`rust
fn fibonacci(n: u32) -> u32 {
    match n {
        0 => 0,
        1 => 1,
        _ => fibonacci(n - 1) + fibonacci(n - 2),
    }
}

fn main() {
    for i in 0..10 {
        println!("fibonacci({}) = {}", i, fibonacci(i));
    }
}
\`\`\`

EOF
done

# Add final closing content.
cat << 'EOF'

---

## Conclusion

This fixture document is designed to be representative of real-world Markdown documents
that developers might work with, including READMEs, design documents, and technical specs.

The mix of code blocks, tables, lists, and inline formatting provides a realistic workload
for benchmarking the rendering pipeline.

Generated deterministically for reproducible performance measurements across runs and machines.

---

*End of fixture document.*
EOF

# Restore the real stdout before anything further is written.
exec 1>&3 3>&-

# Move the temp file to the output location atomically.
mv "$TEMP_FILE" "$OUTPUT_FILE"

# Report the file size and location.
SIZE=$(stat -f%z "$OUTPUT_FILE" 2>/dev/null || stat -c%s "$OUTPUT_FILE" 2>/dev/null || echo "unknown")
echo "Generated $OUTPUT_FILE ($SIZE bytes)"
